name: Run tests

on: [push]

jobs:
  example-1:
    name: Testing (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - name: Configure conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Check repo out
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Run tests
        run: |
          ls -a;
          $CONDA/bin/pytest
