name: Python Package Using Anaconda

on: [push]

jobs:
  example-1:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base
      - name: Run tests
        run: |
          $CONDA/bin/pytest
